/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.abuhck.advent;

public class App {

    public static void main(String[] args) {
//        new Day1();
//        new Day2();
//        new Day3();
//        new Day4();
//        new Day5();
//        new Day6();
//        new Day7();
        new Day8();
    }

}
